apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-devops
  template:
    metadata:
      labels:
        app: projeto-devops
    spec:
      containers:
      - name: projeto-devops
        image: weslley7/projeto-devops:{{tag}}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: projeto-devops
spec:
  selector:
    app: projeto-devops
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  type: NodePort
